version: '3.4'
services:
  hd-wallet.gateways-api:
    image: hd-wallet.gateways-api
    container_name:  hd-wallet.gateways-api
    build:
      context: ./
      dockerfile: Gateways/HD.Wallet.Gateway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - 8000:8000
    restart: always

  hd-wallet.account-api:
    image: hd-wallet.account-api
    container_name:  hd-wallet.account-api
    build:
      context: ./
      dockerfile: Services/HD.Wallet.Account.Service/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - 8100:8100
    restart: always

  hd-wallet.transaction-api:
    image: hd-wallet.transaction-api
    container_name:  hd-wallet.transaction-api
    build:
      context: ./
      dockerfile: Services/HD.Wallet.Transaction.Service/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - 8200:8200
    restart: always
  
  hd-wallet.identity-api:
    image: hd-wallet.identity-api
    container_name:  hd-wallet.identity-api
    build:
      context: ./
      dockerfile: Services/HD.Wallet.Identity.Service/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - 8300:8300
    restart: always